### PR TITLE
Frontend Conversational Update

### PR DESCRIPTION
**Pull request by GitMarco27**
Hi! Based on your suggestions (@shroominic), I worked on a conversational #8 version of the front end. It's possible to

- upload files
- converse with the chatbot
- display images
- reset the conversation 
- write your OpenAI key directly from the UI if desired

Screenshot 2023-07-24 at 10 46 31

I would need your review on two points:

1. Once an image has been generated, the session returns it each time, even if not required. This ensures that once an image has been plotted, it will be displayed again in subsequent messages. Is this desired behaviour on the part of 'CodeInterpreterSession'?
2. If I ask for a new image, when at least one has already been displayed, I get a 'websockets.exceptions.ConnectionClosedError'. I am finding it difficult to debug this, I was wondering if such a problem had already occurred during development. In order to replicate the bug, it is sufficient to ask to display a plot and then immediately ask to display a different one.

### CODE REVIEW

**Comment by shroominic** [comment]
Hey I pushed some stuff to this branch maybe we can also discuss on a discord call how to best write this :)

**Comment by shroominic** [comment]
The session management was a but wrong I tried to fix is but not sure if its bug free haha - got this result tho looks great!
Screenshot 2023-07-28 at 17 54 13

**Comment by shroominic** [comment]
https://github.com/shroominic/codeinterpreter-api/tree/GitMarco27/main
My commits are on this branch idk if its possible to link these to this PR ...

**Comment by shroominic** [comment]
Also I saw this https://github.com/mahm/codeinterpreter-streamlit there are some ideas that could help you @GitMarco27

**Comment by shroominic** [comment]
Screenshot 2023-07-28 at 18 44 40

File output is still not working any idea on how this could be done?

**Comment by shroominic** [comment]
Hey @GitMarco27 how are you doing have you looked at the changes I made?

**Comment by GitMarco27** [comment]
> Hey @GitMarco27 how are you doing have you looked at the changes I made?

Hi! I apologize for my inactivity, I have had a lot of work commitments. I will check your changes these days and contact you as soon as possible.

**Comment by shroominic** [comment]
No worries just take your time. 
I pushed some new stuff in v0.0.10 and I think its doing some conflicts maybe you can also check this.
But really good work! Excited to merge soon :)

**Pull request closed without merging**
