### PR TITLE
Allow custom system message, custom max_iterations

### PR DESCRIPTION
**Pull request by preritdas**
Allow a user to optionally provide a `SystemMessage` object to the `CodeInterpreterSession` instantiation. If they don't, fall back to the system message previously defined. 

Also, allow a user to optionally provide a `max_iterations` value at instantiation, which will default to the current value of `9` if not provided.

### CODE REVIEW

**Comment by preritdas** [comment]
Can you take a look at this please @shroominic?

**Comment by shroominic** [comment]
Yeah looks good! I want to merge it with v0.0.12 but currently need to do a lot of private stuff so it will take a few days until I can focus on this again. But in the meantime if you really need this in your app or so you can pip install from your forked repo `pip install git+https://github.com/preritdas/codeinterpreter-api.git@custom-system-message#egg=codeinterpreterapi`

**Comment by preritdas** [comment]
Thanks, no worries. Let me know if you need any help or modifications.

**Comment by shroominic** [comment]
Hey I was checking the PR again
What do you think of directly use the kwargs for max_iterations?
`self.llm: BaseLanguageModel = llm or self._choose_llm(**kwargs)` <--

**Comment by shroominic** [comment]
But in general looks very good I will merge after we discussed this :)

**Comment by preritdas** [comment]
Well the max_iterations param is going to the AgentExecutor creation not the LLM so I don't see how that would help, but let me know if I'm missing something?

**Comment by shroominic** [comment]
> Well the max_iterations param is going to the AgentExecutor creation not the LLM so I don't see how that would help, but let me know if I'm missing something?

Yeah you are right I just forgot how my code works xD

**Pull request merged**
